[phases.setup]
nixPkgs = ["python312", "libjpeg", "zlib", "libpng", "freetype"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python app.py"
